# Generated by Django 5.1.2 on 2024-11-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
